### ISSUE TITLE
问题求教

### ISSUE THREAD

**Issue by timercrack** [xdedss/cvmaj#1]
你好，我最近在研究雀魂的图像识别方法，遇到些问题想有偿向你请教一下，可否留个联系方式？我的邮箱 timercrack@gmail.com

**Comment by xdedss** [comment]
如果对本项目相关内容有疑问可以直接在这里讨论

**Comment by timercrack** [comment]
在实际的纯图像识别对战中，如果要配合AI的话，还需要获取副露和手模切的信息，这个不太好弄，请问你有什么思路吗？谢谢！

**Comment by xdedss** [comment]
副露的位置看起来比较固定，应该可以用识别牌河类似的方法识别出来。切牌的话感觉比较难了，只有不到一秒钟的时间窗口，还有手的遮挡，如果能精准截取手伸出来前后的画面可以作差得出哪张消失，但是这个时间怎么把握我也想不到什么好方法

**Comment by timercrack** [comment]
感谢，截图我可以通过直接读取显存获取每一帧图像，具体怎么做差得出消失还不太明白。
还有个问题就是，我看你在提取牌河的时候先做了透射变换，如果要识别副露也需要做同样的操作再进行图像识别。可是副露的位置并没有参考线，如何确定计算变换矩阵的四个点呢？
或者我想能不能不做透射变换，直接从原始图像中提取牌的图像（可能是个梯形的，不知道该如何提取），拉伸成32x32给模型训练，这样有办法做到吗？

**Comment by xdedss** [comment]
1. 理论上如果没有其他动画效果的遮挡，切牌前后只有一张牌消失了，其他地方像素值不变，那么前后图像作差就能看出哪张消失了，从而根据位置判断手摸切
2. 桌子上的牌都在同一个平面上所以透视变换可以用同一组参考点，只需要再平移一下
```
    mat = cv2.getPerspectiveTransform(v32(ulc, urc, blc, brc), 
        v32([0, 0], [size, 0], [0, size], [size, size]))
```
这里面[0, 0], [size, 0], [0, size], [size, size]表示映射后的四个点恰好对着图像的四个角，给他平移变成[x, y], [size+x, y], [x, size+y], [size+x, size+y]就可以看到本来被映射到画面外的区域

**Comment by timercrack** [comment]
原来如此，万分感谢！方便邮箱发我个QQ之类的吗？
